import { t } from "./i18n";

const API_ERROR_KEYS = {
  "Not authenticated": "api.not_authenticated",
  Forbidden: "api.forbidden",
  "Not Found": "api.not_found",
  "Invalid JSON": "api.invalid_json",
  "File not found": "api.file_not_found",
  "Asset file not found": "api.asset_file_not_found",
  Trashed: "api.trashed",
  "Invalid name": "api.invalid_name",
  "Invalid query": "api.invalid_query",
  "No updates": "api.no_updates",
  "id is required": "api.id_required",
  "Invalid file_id": "api.invalid_file_id",
  "file_id must be an integer": "api.invalid_file_id",
  "Invalid user_id": "api.invalid_user_id",
  "user_id must be an integer": "api.invalid_user_id",
  "User not found": "api.user_not_found",
  "MariaDB unavailable": "api.mariadb_unavailable",
  "Invalid credentials": "api.invalid_credentials",
  "Too many login attempts. Try again later.": "api.too_many_login_attempts",
  "Missing fields": "api.missing_fields",
  "Passwords do not match": "api.passwords_do_not_match",
  "Current password is incorrect": "api.current_password_incorrect",
  "Invalid username": "api.invalid_username",
  "Username already exists": "api.username_exists",
  "Password is required": "api.password_required",
  "Password must be at least 8 characters": "api.password_too_short",
  "Cannot delete your own user": "api.cannot_delete_own_user",
  "Saved search already exists": "api.saved_search_exists",
  "Invalid language code": "api.invalid_language_code",
  "Language names are required": "api.language_names_required",
  "Language already exists": "api.language_exists",
  "Invalid string key": "api.invalid_string_key",
  "Default English text is required": "api.default_english_required",
  "String key already exists": "api.string_key_exists",
  "String key is required": "api.string_key_required",
  "Translated text is required": "api.translated_text_required",
  "Language not found": "api.language_not_found",
  "Invalid tag name": "api.invalid_tag_name",
  "Invalid tag type": "api.invalid_tag_type",
  "Tag already exists": "api.tag_exists",
  "Parent tag not found": "api.parent_tag_not_found",
  "Parent tag cannot equal tag": "api.parent_tag_self",
  "Semantic tag not found": "api.semantic_tag_not_found",
  "Cannot delete tag with children": "api.cannot_delete_tag_with_children",
  "search_query is required for all_results": "api.search_query_required_for_all_results",
  "No matching media found": "api.no_matching_media_found",
  "Cannot favorite trashed media": "api.favorite_trashed_forbidden",
  "Only images are supported": "api.only_images_supported",
  "Only videos are supported": "api.only_videos_supported",
  "Please select files first (max 20)": "api.download_select_files_first",
  "More than 20 files selected, please unselect some": "api.download_too_many_files",
  "Some selected media files were not found": "api.download_media_missing",
  "Some selected assets were not found": "api.download_assets_missing",
  "Trashed media cannot be downloaded": "api.download_trashed_forbidden",
  "Only image/video media files are supported": "api.download_only_media_supported",
  "Only audio/document assets are supported": "api.download_only_assets_supported",
  "File outside configured photos root": "api.file_outside_root",
  "Asset outside configured photos root": "api.asset_outside_root",
  "No files selected": "api.no_files_selected",
  "Setup already completed": "api.setup_completed",
  "query must be an object": "api.query_must_be_object",
  "query.where is required": "api.query_where_required",
  "Invalid destination folder": "api.invalid_destination_folder",
  "Source and destination folders are the same": "api.move_same_folder",
  "Destination already contains a file with this name": "api.destination_file_exists",
  "Failed to move file on disk": "api.disk_move_failed",
  "Indexer move failed and original file was restored": "api.indexer_move_failed_restored",
  "Indexer move failed and rollback failed": "api.indexer_move_failed_rollback_failed",
  "Only image/video media files are supported": "api.only_media_files_supported",
  "Move blocked: open tag edits exist for this media": "api.move_blocked_open_tag_edits",
  "Move blocked: a tag-edit job is active for this media": "api.move_blocked_media_tag_job_running",
  "Move blocked: a transform job is active for this object": "api.move_blocked_transform_job_running",
  "MariaDB move sync failed and original file was restored": "api.maria_move_sync_failed_restored",
  "MariaDB move sync failed and rollback failed": "api.maria_move_sync_failed_rollback_failed",
  "Only audio assets are supported": "api.only_audio_assets_supported",
  "Only document assets are supported": "api.only_document_assets_supported",
  "Only supported assets can be moved": "api.only_supported_assets_can_be_moved",
  "Asset move blocked: a running derivative job exists for this asset": "api.asset_move_blocked_running_derivative_job",
  "Could not resolve collision-free target filename": "api.move_collision_resolution_failed",
  "Asset move DB sync failed and original file was restored": "api.asset_move_db_sync_failed_restored",
  "Asset move DB sync failed and rollback failed": "api.asset_move_db_sync_failed_rollback_failed",
  "ids are required": "api.ids_required",
  "Too many items. Move in batches of up to 500": "api.batch_move_too_many_items",
  "Unsupported move item id": "api.batch_move_unsupported_item_id",
  "Invalid parent folder": "api.invalid_parent_folder",
  "Invalid folder name": "api.invalid_folder_name",
  "Invalid folder path": "api.invalid_folder_path",
  "Folder already exists": "api.folder_already_exists",
  "Failed to create folder": "api.folder_create_failed",
  "Folder not found": "api.folder_not_found",
  "Folder is not empty": "api.folder_not_empty",
  "Failed to delete folder": "api.folder_delete_failed",
  "Undo not available: no move history": "api.undo_not_available_no_history",
  "Undo not available: newer move exists": "api.undo_not_available_newer_move_exists",
  "Undo not available: current path mismatch": "api.undo_not_available_current_path_mismatch",
  "Undo not available: item missing": "api.undo_not_available_item_missing",
  "Undo not available: original destination missing": "api.undo_not_available_original_destination_missing",
  "Undo not available: blocked by active work": "api.undo_not_available_blocked_active_work",
  "Undo failed": "api.undo_failed"
};

export function apiErrorMessage(serverMessage, fallbackKey = "", fallbackText = "") {
  const message = typeof serverMessage === "string" ? serverMessage.trim() : "";
  if (message && API_ERROR_KEYS[message]) {
    return t(API_ERROR_KEYS[message], message);
  }
  if (message) {
    return message;
  }
  if (fallbackKey) {
    return t(fallbackKey, fallbackText || fallbackKey);
  }
  return fallbackText || "";
}
